version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: http-laravel_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000  
    depends_on:
        - db
    container_name: http-laravel_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=http5
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8101:3306
    container_name: http-laravel_db          

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306        

volumes:
  database: